---
# configure httpd.conf & sending sample html file
- name: httpd.conf file
  copy: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
  notify: 
     restart apache service 

- name: send index.hlml
  copy: src=index.html dest=/var/www/html/index.html

